/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BoceAppointmentData {
        "patient": any;
    }
    interface BoceCreatePatient {
        "entryId": string;
    }
    interface BoceCreateTerm {
    }
    interface BoceDoctorPatientsList {
    }
    interface BoceLogin {
    }
    interface BoceMyAppointments {
    }
    interface BocePatientData {
    }
    interface BocePatientSearch {
    }
    interface BocePlannedAppointments {
    }
    interface BoceReserveAppointment {
    }
    interface BoceWacProjectApp {
        "basePath": string;
    }
}
export interface BocePatientDataCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBocePatientDataElement;
}
declare global {
    interface HTMLBoceAppointmentDataElement extends Components.BoceAppointmentData, HTMLStencilElement {
    }
    var HTMLBoceAppointmentDataElement: {
        prototype: HTMLBoceAppointmentDataElement;
        new (): HTMLBoceAppointmentDataElement;
    };
    interface HTMLBoceCreatePatientElement extends Components.BoceCreatePatient, HTMLStencilElement {
    }
    var HTMLBoceCreatePatientElement: {
        prototype: HTMLBoceCreatePatientElement;
        new (): HTMLBoceCreatePatientElement;
    };
    interface HTMLBoceCreateTermElement extends Components.BoceCreateTerm, HTMLStencilElement {
    }
    var HTMLBoceCreateTermElement: {
        prototype: HTMLBoceCreateTermElement;
        new (): HTMLBoceCreateTermElement;
    };
    interface HTMLBoceDoctorPatientsListElement extends Components.BoceDoctorPatientsList, HTMLStencilElement {
    }
    var HTMLBoceDoctorPatientsListElement: {
        prototype: HTMLBoceDoctorPatientsListElement;
        new (): HTMLBoceDoctorPatientsListElement;
    };
    interface HTMLBoceLoginElement extends Components.BoceLogin, HTMLStencilElement {
    }
    var HTMLBoceLoginElement: {
        prototype: HTMLBoceLoginElement;
        new (): HTMLBoceLoginElement;
    };
    interface HTMLBoceMyAppointmentsElement extends Components.BoceMyAppointments, HTMLStencilElement {
    }
    var HTMLBoceMyAppointmentsElement: {
        prototype: HTMLBoceMyAppointmentsElement;
        new (): HTMLBoceMyAppointmentsElement;
    };
    interface HTMLBocePatientDataElementEventMap {
        "entry-clicked": string;
        "logout-clicked": string;
        "list-clicked": string;
    }
    interface HTMLBocePatientDataElement extends Components.BocePatientData, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBocePatientDataElementEventMap>(type: K, listener: (this: HTMLBocePatientDataElement, ev: BocePatientDataCustomEvent<HTMLBocePatientDataElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBocePatientDataElementEventMap>(type: K, listener: (this: HTMLBocePatientDataElement, ev: BocePatientDataCustomEvent<HTMLBocePatientDataElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBocePatientDataElement: {
        prototype: HTMLBocePatientDataElement;
        new (): HTMLBocePatientDataElement;
    };
    interface HTMLBocePatientSearchElement extends Components.BocePatientSearch, HTMLStencilElement {
    }
    var HTMLBocePatientSearchElement: {
        prototype: HTMLBocePatientSearchElement;
        new (): HTMLBocePatientSearchElement;
    };
    interface HTMLBocePlannedAppointmentsElement extends Components.BocePlannedAppointments, HTMLStencilElement {
    }
    var HTMLBocePlannedAppointmentsElement: {
        prototype: HTMLBocePlannedAppointmentsElement;
        new (): HTMLBocePlannedAppointmentsElement;
    };
    interface HTMLBoceReserveAppointmentElement extends Components.BoceReserveAppointment, HTMLStencilElement {
    }
    var HTMLBoceReserveAppointmentElement: {
        prototype: HTMLBoceReserveAppointmentElement;
        new (): HTMLBoceReserveAppointmentElement;
    };
    interface HTMLBoceWacProjectAppElement extends Components.BoceWacProjectApp, HTMLStencilElement {
    }
    var HTMLBoceWacProjectAppElement: {
        prototype: HTMLBoceWacProjectAppElement;
        new (): HTMLBoceWacProjectAppElement;
    };
    interface HTMLElementTagNameMap {
        "boce-appointment-data": HTMLBoceAppointmentDataElement;
        "boce-create-patient": HTMLBoceCreatePatientElement;
        "boce-create-term": HTMLBoceCreateTermElement;
        "boce-doctor-patients-list": HTMLBoceDoctorPatientsListElement;
        "boce-login": HTMLBoceLoginElement;
        "boce-my-appointments": HTMLBoceMyAppointmentsElement;
        "boce-patient-data": HTMLBocePatientDataElement;
        "boce-patient-search": HTMLBocePatientSearchElement;
        "boce-planned-appointments": HTMLBocePlannedAppointmentsElement;
        "boce-reserve-appointment": HTMLBoceReserveAppointmentElement;
        "boce-wac-project-app": HTMLBoceWacProjectAppElement;
    }
}
declare namespace LocalJSX {
    interface BoceAppointmentData {
        "patient"?: any;
    }
    interface BoceCreatePatient {
        "entryId"?: string;
    }
    interface BoceCreateTerm {
    }
    interface BoceDoctorPatientsList {
    }
    interface BoceLogin {
    }
    interface BoceMyAppointments {
    }
    interface BocePatientData {
        "onEntry-clicked"?: (event: BocePatientDataCustomEvent<string>) => void;
        "onList-clicked"?: (event: BocePatientDataCustomEvent<string>) => void;
        "onLogout-clicked"?: (event: BocePatientDataCustomEvent<string>) => void;
    }
    interface BocePatientSearch {
    }
    interface BocePlannedAppointments {
    }
    interface BoceReserveAppointment {
    }
    interface BoceWacProjectApp {
        "basePath"?: string;
    }
    interface IntrinsicElements {
        "boce-appointment-data": BoceAppointmentData;
        "boce-create-patient": BoceCreatePatient;
        "boce-create-term": BoceCreateTerm;
        "boce-doctor-patients-list": BoceDoctorPatientsList;
        "boce-login": BoceLogin;
        "boce-my-appointments": BoceMyAppointments;
        "boce-patient-data": BocePatientData;
        "boce-patient-search": BocePatientSearch;
        "boce-planned-appointments": BocePlannedAppointments;
        "boce-reserve-appointment": BoceReserveAppointment;
        "boce-wac-project-app": BoceWacProjectApp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "boce-appointment-data": LocalJSX.BoceAppointmentData & JSXBase.HTMLAttributes<HTMLBoceAppointmentDataElement>;
            "boce-create-patient": LocalJSX.BoceCreatePatient & JSXBase.HTMLAttributes<HTMLBoceCreatePatientElement>;
            "boce-create-term": LocalJSX.BoceCreateTerm & JSXBase.HTMLAttributes<HTMLBoceCreateTermElement>;
            "boce-doctor-patients-list": LocalJSX.BoceDoctorPatientsList & JSXBase.HTMLAttributes<HTMLBoceDoctorPatientsListElement>;
            "boce-login": LocalJSX.BoceLogin & JSXBase.HTMLAttributes<HTMLBoceLoginElement>;
            "boce-my-appointments": LocalJSX.BoceMyAppointments & JSXBase.HTMLAttributes<HTMLBoceMyAppointmentsElement>;
            "boce-patient-data": LocalJSX.BocePatientData & JSXBase.HTMLAttributes<HTMLBocePatientDataElement>;
            "boce-patient-search": LocalJSX.BocePatientSearch & JSXBase.HTMLAttributes<HTMLBocePatientSearchElement>;
            "boce-planned-appointments": LocalJSX.BocePlannedAppointments & JSXBase.HTMLAttributes<HTMLBocePlannedAppointmentsElement>;
            "boce-reserve-appointment": LocalJSX.BoceReserveAppointment & JSXBase.HTMLAttributes<HTMLBoceReserveAppointmentElement>;
            "boce-wac-project-app": LocalJSX.BoceWacProjectApp & JSXBase.HTMLAttributes<HTMLBoceWacProjectAppElement>;
        }
    }
}
